	<?php 
		$enable = $block->getConfig('enabled');
		if($enable < 1) return ; 
		$items = $block->getConfig('items');
		$speed = $block->getConfig('speed');
		$qty = $block->getConfig('qty');
		$showCart = $block->getConfig('addtocart');
		$showWishlist = $block->getConfig('wishlist');
		$showCompare = $block->getConfig('compare');
		$show_navigation = $block->getConfig('navigation');
		$show_pagination = $block->getConfig('pagination');
		$auto = $block->getConfig('auto');
		$imageBlock =  $block->getLayout()->createBlock('Magento\Catalog\Block\Product\Image');
		$image = 'new_products_content_widget_grid';
		$type = 'widget-new-grid';
		$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
		$rows = $block->getConfig('row');
		$myHelper = $this->helper('Plazathemes\Themeoptions\Helper\Data');
	?>

	<div class="title-product">
		<h3><?php /* @escapeNotVerified */ echo __('Top Interesting'); ?></h3>
		<p><?php /* @escapeNotVerified */ echo __('Browse the collection of our best selling and top interesting products.'); ?></p>
		<p><?php /* @escapeNotVerified */ echo __('TYou’ll definitely find what you are looking for.'); ?></p>
	</div>
	
	<div class="group-title1 title-tab">
		<ul class="tabs">
			<?php 
				$tab_contents = $block->getTabContent() ; 
				$count=0;			
			foreach($tab_contents as $tab) {
				?>
			<li rel="tab_<?php echo $tab['id'];?>"  class="<?php if ($count==0): ?>first active <?php endif; ?><?php if ($count == (count($tab_contents) - 1)): ?>last<?php endif; ?>" > <?php echo $tab['name'];?></li>
				<?php
				$count ++; 
			}
			?>
		</ul>
	</div>	

	<div class="tab_container producttab_inner"> 
	   <?php 
		foreach($tab_contents as $tab) {
		?>
		
		<div class="row">
			<div class="owl-container">
				<div id="tab_<?php echo $tab['id'];?>" class="tab_content"> 
					<div class="productTabContent owl-carousel">
						<?php 
							$i=0;
							$productItems =  $tab['productInfo']; 
							foreach($productItems as $_item) { 
								if($_item->getRotaryImage())
									$imageRotary = $myHelper->getMedia_Url().'catalog/product/'.$_item->getRotaryImage();
								else
									$imageRotary = '';   
									$productImage = $block->getImage($_item, $image);
							?>
								<?php if($i++%$rows==0) { ?> <div class="product_row"> <?php $count_r = 0; } ?>
								<div class="item products-grid">
									<div class="item-inner">
										<div class="product-item-info">
											<div class="image-container ">
												<a href="<?php echo $block->getProductUrl($_item) ?>" 
													class="product-item-photo"
												>
													<?php echo $productImage->toHtml() ?>
													<span class="image-rotator">
														<?php if($imageRotary): ?>
														  <img src="<?php echo $imageRotary; ?>" alt="" />
														 <?php else: ?>
														  <?php echo $productImage->toHtml() ?>
														 <?php endif; ?>
													</span>						
												</a>
											</div>	
											<div class="product-item-details">
												<?php if ($templateType): ?>
													<?php echo $block->getReviewsSummaryHtml($_item, $templateType,true); ?>
												<?php endif; ?>
												<div class="product-name">
													<strong class="product-item-name">
														<a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
														   href="<?php echo $block->getProductUrl($_item) ?>"
														   class="product-item-link">
															<?php echo $block->escapeHtml($_item->getName()) ?>
														</a>
													</strong>
												</div>
												 <?php
													echo $block->getProductPrice($_item);
												 ?>
												 <div class="box-hover">
													<?php if ($showCart): ?>
														<div class="actions-primary">
															<?php if ($_item->isSaleable()): ?>
																<?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
																	<button class="action tocart primary"
																		data-mage-init='{"redirectUrl":{"url":"<?php echo $block->getAddToCartUrl($_item) ?>"}}'
																			type="button" 
																			title="<?php echo __('Add to Box') ?>">
																		<span><?php echo __('Add to Box') ?></span>
																	</button>
																<?php else: ?>
																	<?php
																		$postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
																		$postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
																	?>
																	<button class="action tocart primary"
																			data-post='<?php echo $postData; ?>'
																			type="button" title="<?php echo __('Add to cart') ?>">
																		<span><?php echo __('Add to cart') ?></span>
																	</button>
																<?php endif; ?>
															<?php else: ?>
																<?php if ($_item->getIsSalable()): ?>
																	<div class="stock available"><span><?php echo __('In stock') ?></span></div>
																<?php else: ?>
																	<div class="stock unavailable"><span><?php echo __('Out of stock') ?></span></div>
																<?php endif; ?>
															<?php endif; ?>
														</div>
													<?php endif; ?>
													<?php if ($showWishlist || $showCompare || $showCart): ?>
														<?php if ($showWishlist || $showCompare): ?>
															<div class="add-to-links actions-secondary" data-role="add-to-links">
																<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
																	<a href="#"
																	   data-post='<?php echo $block->getAddToWishlistParams($_item); ?>'
																	   class="action towishlist" data-action="add-to-wishlist"
																	   title="<?php echo __('Add to Wishlist') ?>">
																		<span><?php echo __('Wishlist') ?></span>
																	</a>
																<?php endif; ?>
																<?php if ($block->getAddToCompareUrl() && $showCompare): ?>
																	<?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');?>
																	<a href="#" class="action tocompare"
																	   data-post='<?php echo $compareHelper->getPostDataParams($_item);?>'
																	   title="<?php echo __('Add to Compare') ?>">
																		<span><?php echo __('Compare') ?></span>
																	</a>
																<?php endif; ?>
															</div>
														<?php endif; ?>
													<?php endif; ?>
												</div>
											</div>
										</div>
									</div>	
								</div>
								 <?php if($i%$rows==0 || $i == count($productItems)) { ?> </div> <?php }?>
							<?php 
							}
						?>
					</div>
				</div>
			</div> 
		</div>
		<?php 
		} 
		?>
	</div>

	
<script type="text/javascript">
	require([
	  "jquery",
	  "owlcarousel/minjs"
	 ], function($,owlCarousel){

		$(".tab_content").hide();
		$(".tab_content:first").show(); 
		$("ul.tabs li").removeClass("active");
		$("ul.tabs li:first-child").addClass("active");
		$("ul.tabs li").click(function() {
			$("ul.tabs li").removeClass("active");
			$(this).addClass("active");
			$(".tab_content").hide();
			$(".tab_content").removeClass("animate1");
			var activeTab = $(this).attr("rel"); 
			$("#"+activeTab) .addClass("animate1");
			$("#"+activeTab).fadeIn(); 
		});
		
		$(".productTabContent").owlCarousel({
    		items : <?php if($items) { echo $items; } else { echo 5; }?>,
			autoPlay : <?php if($auto) echo 'true'; else echo 'false'; ?>,
			slideSpeed : <?php if($speed) echo $speed; else echo '500'; ?>,
			navigation : false,
			stopOnHover : true,
			pagination :true,
			pagination : true,
			items : 6,
			itemsDesktop : [1600,6],
			itemsDesktopSmall : [1199,4],
			itemsTablet: [991,3],
			itemsTabletSmall: [768,3],
			itemsMobile : [480,2],
			addClassActive: true,
			afterAction: function(el){
				 this.$owlItems.removeClass('before-active')
				 this.$owlItems.removeClass('last-active')
				 this.$owlItems .eq(this.currentItem).addClass('before-active')  
				 this.$owlItems .eq(this.currentItem + (this.owl.visibleItems.length - 1)).addClass('last-active')
			  }
		});
	});
</script> 
