<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<div class="product-options-bottom">
    <?php echo $block->getChildHtml('', true);?>
</div>

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.9&appId=231723633976400";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<div class="ShareProduct">
	<ul>
		<li>
			<div class="fb-share-button" data-href="<?php echo $this->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]) ?>" data-layout="button_count" data-size="small" data-mobile-iframe="true">
				<a class="fb-xfbml-parse-ignore" target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=<?php echo $this->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]) ?>">Share</a>
			</div>
		</li>
		<li>
			<a href="https://twitter.com/share" class="twitter-share-button" data-show-count="false">Tweet</a><script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>			
		</li>
		<li>
			<script type="text/javascript" async defer src="//assets.pinterest.com/js/pinit.js"></script>
			<a href="https://www.pinterest.com/pin/create/button/">
			    <img src="//assets.pinterest.com/images/pidgets/pinit_fg_en_rect_gray_20.png" />
			</a>			
		</li>		
		<li>
			<script src="https://apis.google.com/js/platform.js" async defer></script>
			<g:plusone size="medium"></g:plusone>
		</li>
	</ul>	
</div>
