<div class="main-container col2-left-layout">	
	<div class="home-conten">	
		<div class="subscribe-new">
			<div class="container-inner">	
				<div class="subscribe1">
					<?php echo $block->getLayout()->createBlock('Magento\Newsletter\Block\Subscribe')->setTemplate('Magento_Newsletter::subscribe.phtml')->toHtml();?>
				</div>
			</div>	
		</div>
		<div class="intagaram">
			<?php echo $block->getLayout()->createBlock('Plazathemes\InstagramGallery\Block\InstagramGallery')->setTemplate('Plazathemes_InstagramGallery::plazathemes/instagramgallery/default.phtml')->toHtml();?>
		</div>
	</div>
</div>

<div class="footer-container">
	<div class="footer-border"></div>
	<div class="footer-top">
		<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_global')->toHtml();?>
		<div id="back_top">
			<a href="#back-top"><span>>top</span></a>
		</div>
		<?php echo $this->getChildHtml("store_switcher"); ?>
	</div>
</div>

<script type="text/javascript">
	require(["jquery"], function($) {
	   $(window).scroll(function() {
			if($(this).scrollTop() > 300) {
				$('#back_top').fadeIn();   
			} else {
				$('#back_top').fadeOut();
			}
		});

		$('#back_top').click(function() {
			$('body,html').animate({scrollTop:0},500);
		}); 
		
		if (jQuery(window).width() < 767) {   
			jQuery('.footer-static .footer-static-title').click(function(){     
				jQuery(this).parent('.col-xs').toggleClass('active').siblings().removeClass('active'); 
				jQuery(this).next('.col-xs .footer-static-content').toggle(300);
				jQuery(this).parent('.col-xs.active').siblings().children('.col-xs .footer-static-content').slideUp(300); 
			}); 
		}
	});
</script>