<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * BSS Commerce does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * BSS Commerce does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   BSS
 * @package    Bss_OrderDeliveryDate
 * @author     Extension Team
 * @copyright  Copyright (c) 2015-2016 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
?>
<?php
    $day_off = $this->helper('Bss\OrderDeliveryDate\Helper\Data')->getDayOff();
    $block_out_holidays = unserialize($this->helper('Bss\OrderDeliveryDate\Helper\Data')->getBlockHoliday());
    $process_time = 0; 
    $current_time = (int) $block->getStoreTimestamp();
    $cut_off_time_convert = $this->helper('Bss\OrderDeliveryDate\Helper\Data')->getCutOffTime();
    $process_time = $this->helper('Bss\OrderDeliveryDate\Helper\Data')->getProcessingTime();
    if($cut_off_time_convert && $current_time > $cut_off_time_convert){
        $process_time = $process_time + 1;
    }
?>

<script>
    var trigger = false;
    var previousDate = "";
    var block_out_holidays = [];
    var day_off_arr = [];
    var day_off = '<?php echo $day_off;?>';
    day_off_arr = day_off.split(',');
    block_out_holidays = '<?php echo json_encode($block_out_holidays);?>';
    require([
          'jquery',
          'mage/calendar'
        ], function ( $ ) {
          $.extend(true, $, {
            calendarConfig: { 
                minDate: <?php echo $process_time;?>,
                infoTitle: "<?php /* @escapeNotVerified */ echo __('About the calendar');?>",
                firstDay: 0,
                closeText: "<?php /* @escapeNotVerified */ echo __('Close');?>",
                currentText: "<?php /* @escapeNotVerified */ echo __('Go Today'); ?>",
                prevText: "<?php /* @escapeNotVerified */ echo __('Previous');?>",
                nextText: "<?php /* @escapeNotVerified */ echo __('Next');?>",
                weekHeader: "<?php /* @escapeNotVerified */ echo __('WK'); ?>",
                timeText: "<?php /* @escapeNotVerified */ echo __('Time');?>",
                hourText: "<?php /* @escapeNotVerified */ echo __('Hour');?>",
                minuteText: "<?php /* @escapeNotVerified */ echo __('Minute');?>",
                dateFormat: $.datepicker.RFC_2822,
                showOn: "button",
                showAnim: "",
                changeMonth: false,
                changeYear: false,
                buttonImageOnly: null,
                buttonImage: null,
                showButtonPanel: true,
                showOtherMonths: true,
                showWeek: false,
                timeFormat: '',
                showTime: false,
                showHour: false,
                showMinute: false,
                serverTimezoneSeconds: <?php echo (int) $block->getStoreTimestamp(); ?>,
                serverTimezoneOffset: <?php echo (int) $block->getTimezoneOffsetSeconds(); ?>,
                beforeShowDay: function(date){
                    var string = jQuery.datepicker.formatDate('yy-mm-dd', date);
                    var day = date.getDay();
                    for (i = 0;i < day_off_arr.length; i++){
                        day_off_arr[i] = parseInt(day_off_arr[i]);
                    }
                    if(day_off_arr.indexOf(day)==-1  && block_out_holidays.indexOf(string) == -1) return[true,''];
                    else return [false,''];
                },

            }
          });
        });
</script>