<div class="product-available-in">
	<p>Available in</p>
	<ul>
		<li><a href="#"><span class="flag-icon flag-icon-ae flag-icon-squared"></span></a></li>
		<li><a href="#"><span class="flag-icon flag-icon-qa flag-icon-squared"></span></a></li>
		<li><a href="#"><span class="flag-icon flag-icon-bh flag-icon-squared"></span></a></li>
		<li><a href="#"><span class="flag-icon flag-icon-om flag-icon-squared"></span></a></li>
		<li><a href="#"><span class="flag-icon flag-icon-kw flag-icon-squared"></span></a></li>
		<li><a href="#"><span class="flag-icon flag-icon-gb flag-icon-squared"></span></a></li>
	</ul>
</div>