<div class="row">
	<div class="col-md-12 header__content--container header__content--right">
		<img src="{{media url="wysiwyg/Slider_photo-min.jpg"}}" alt="The Maison" class="img-responsive" />
		<div class="header__content">
			<h1>Our Philosophy is Excellence</h1>
			<p class="lead">At Maison Des Fleurs, the French tradition of know-how and elegance remains intact and is preciously transmitted by a highly professional florist team, whose creativity, ability and sensibility is unmatched. Just by magic, our expert hands give life to your most glamorous or passionate dreams.</p>	
		</div>
	</div>
</div>

<div class="The-Maison__content">
	<div class="row">
		<div class="col-md-7">
			<div class="The-Maison-Box--container">
				<img src="{{media url="wysiwyg/The-Maison-Box.png"}}" alt="The Maison" class="img-responsive" />
				<div class="The-Maison-Box__content">
					<p>Maison <span>des</span> fleurs</p>
				</div>
			</div>
		</div>
		<div class="col-md-5">
			<h3>Savoir Faire</h3>
			<p>At Maison Des Fleurs, the French tradition of know-how and elegance remains intact and is preciously transmitted by a highly professional florist team, whose creativity, ability and sensibility is unmatched. Just by magic, our expert hands give life to your most glamorous or passionate dreams. At Maison Des Fleurs, each floral creation is unique. Each arrangement is a reflection of who you are and will express your most profound emotions better than any other message, in luxurious and exclusive signature boxes.</p>	
		</div>
	</div>
</div>

<div class="row">
	<div class="col-md-4">
		<div class="The-Maison-Category">
			<img src="{{media url="wysiwyg/the-maison-fleur.jpg"}}" alt="The Maison" class="img-responsive" />
			<p>Fleur</p>
		</div>
	</div>
	<div class="col-md-4">
		<div class="The-Maison-Category">
			<img src="{{media url="wysiwyg/the-maison-staff.jpg"}}" alt="The Maison" class="img-responsive" />
			<p>Staff</p>
		</div>
	</div>
	<div class="col-md-4">
		<div class="The-Maison-Category">
			<img src="{{media url="wysiwyg/the-maison-retail.jpg"}}" alt="The Maison" class="img-responsive" />
			<p>Retail</p>
		</div>
	</div>		
</div>
