<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * BSS Commerce does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * BSS Commerce does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   BSS
 * @package    Bss_OrderDeliveryDate
 * @author     Extension Team
 * @copyright  Copyright (c) 2015-2016 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
?>
<?php /** @var $block \Magento\Sales\Block\Adminhtml\Order\View\Tab\Info */ ?>
<?php $_order = $block->getOrder() ?>
<?php
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $helper = $objectManager->create('Bss\OrderDeliveryDate\Helper\Data');
?>
<div id="order-messages">
    <?php echo $block->getChildHtml('order_messages') ?>
</div>

<?php echo $block->getChildHtml('order_info') ?>
<input type="hidden" name="order_id" value="<?php /* @escapeNotVerified */ echo $_order->getId() ?>"/>

<section class="admin__page-section order-view-billing-shipping">
    <div class="admin__page-section-title">
        <span class="title"><?php /* @escapeNotVerified */ echo __('Payment &amp; Shipping Method') ?></span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-payment-method<?php if ($_order->getIsVirtual()): ?> order-payment-method-virtual<?php endif; ?>">
            <?php /* Payment Method */ ?>
            <div class="admin__page-section-item-title">
                <span class="title"><?php /* @escapeNotVerified */ echo __('Payment Information') ?></span>
            </div>
            <div class="admin__page-section-item-content">
                <div class="order-payment-method-title"><?php echo $block->getPaymentHtml() ?></div>
                <div class="order-payment-currency"><?php /* @escapeNotVerified */ echo __('The order was placed using %1.', $_order->getOrderCurrencyCode()) ?></div>
                <div class="order-payment-additional">
                    <?php echo $block->getChildHtml('order_payment_additional'); ?>
                    <?php echo $block->getChildHtml('payment_additional_info'); ?>
                </div>
            </div>
        </div>
        <?php echo $block->getChildHtml('order_shipping_view') ?>
    </div>
</section>

<!-- start add delivery date -->
<?php if($helper->isEnabled()):?>
<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?php echo __('Delivery Date Information') ?></span>
    </div>
    <div class="admin__page-section-item order-delivery-date">
            <div class="admin__page-section-item-title">
                <span class="title"><?php echo __('Delivery Date') ?></span>
                <div class="actions">
                    <a href="<?php echo $this->getUrl('orderdeliverydate/order/delivery', ['order_id' => $_order->getId()]); ?>">
                        <?php echo __('Edit') ?>
                    </a>
                </div>
            </div>
            <div class="admin__page-section-item-content">
                <!-- <div class="order-delivery-date-title"><?php echo $block->getChildHtml('order_payment') ?></div> -->
                <div id="shipping-arrival-date">
                    <div>
                        <strong><?php echo __('Shipping Arrival Date: ') ?></strong>
                        <?php if($_order->getShippingArrivalDate()):?>
                            <span><?php echo $_order->getShippingArrivalDate();?></span>
                        <?php else:?>
                            <span><?php echo __('N/A');?></span>
                        <?php endif;?>
                    </div>
                    <div>
                        <strong><?php echo __('Shipping Arrival Timeslot: ') ?></strong>
                        <?php if($_order->getShippingArrivalTimeslot()):?>
                            <span><?php echo $_order->getShippingArrivalTimeslot();?></span>
                        <?php else:?>
                            <span><?php echo __('N/A');?></span>
                        <?php endif;?>
                    </div>
                    <div>
                        <strong><?php echo __('Shipping Arrival Comments: ') ?></strong>
                        <?php if($_order->getShippingArrivalComments()):?>
                            <span><?php echo $_order->getShippingArrivalComments();?></span>
                        <?php else:?>
                            <span><?php echo __('No Comment');?></span>
                        <?php endif;?>
                    </div>
                </div>
            </div>
        </div>
</section>
<?php endif;?>
<!-- end add delivery date -->

<?php echo $block->getGiftOptionsHtml() ?>

<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?php /* @escapeNotVerified */ echo __('Items Ordered') ?></span>
    </div>
    <?php echo $block->getItemsHtml() ?>
</section>

<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?php /* @escapeNotVerified */ echo __('Order Total') ?></span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-comments-history">
            <div class="admin__page-section-item-title">
                <span class="title"><?php /* @escapeNotVerified */ echo __('Notes for this Order') ?></span>
            </div>
            <?php echo $block->getChildHtml('order_history') ?>
        </div>

        <div class="admin__page-section-item order-totals">
            <div class="admin__page-section-item-title">
                <span class="title"><?php /* @escapeNotVerified */ echo __('Order Totals') ?></span>
            </div>
            <?php echo $block->getChildHtml('order_totals') ?>
        </div>
    </div>
</section>

<?php echo $block->getChildHtml('popup_window');?>

<script>
require([
    "prototype",
    "Magento_Sales/order/giftoptions_tooltip"
], function(){

//<![CDATA[
    /**
     * Retrieve gift options tooltip content
     */
    function getGiftOptionsTooltipContent(itemId) {
        var contentLines = [];
        var headerLine = null;
        var contentLine = null;

        $$('#gift_options_data_' + itemId + ' .gift-options-tooltip-content').each(function (element) {
            if (element.down(0)) {
                headerLine = element.down(0).innerHTML;
                contentLine = element.down(0).next().innerHTML;
                if (contentLine.length > 30) {
                    contentLine = contentLine.slice(0,30) + '...';
                }
                contentLines.push(headerLine + ' ' + contentLine);
            }
        });
        return contentLines.join('<br/>');
    }
    giftOptionsTooltip.setTooltipContentLoaderFunction(getGiftOptionsTooltipContent);
    window.getGiftOptionsTooltipContent = getGiftOptionsTooltipContent;
//]]>

});
</script>
