<div class="social-buttons-container">
    <div class="social-buttons--label">
        <p>Share</p>
    </div>

    <div class="social-buttons">
        <?php
            $currentUrl = $block->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]);

            $facebook_share = ($block->showFacebookShare() > 0 ? 'true' : 'false');
            $facebook_count = $block->getFacebookCount();
            $google_count = $block->getGPlusCount();
        ?>
        <?php if ($block->showFacebook()):?>
            
            <div class="fb-share-button" 
                data-href="<?php echo $block->escapeUrl($currentUrl); ?>" 
                data-layout="button" 
                data-show-faces="true" 
                data-share="<?php echo $facebook_share; ?>"
            >
            </div>
            <?php /*
            <div class="fb-share-button"
                data-href="<?php echo $block->escapeUrl($currentUrl); ?>" 
                data-layout="button" 
                data-size="small" 
                data-mobile-iframe="true"
            >
                <a class="fb-xfbml-parse-ignore" target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=<?php echo $block->escapeUrl($currentUrl); ?> ?>">Share</a>
            </div>   
             */ ?>     
        <?php endif ?>
        <?php if ($block->showTwitter()):?>
            <a href="https://twitter.com/share" class="twitter-share-button" data-show-count="false">Tweet</a><script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
        <?php endif ?>
        <?php if ($block->showPinterest()):?>
            <a data-pin-do="buttonBookmark" href="https://www.pinterest.com/pin/create/button/"></a>
        <?php endif ?>
        <?php if ($block->showGPlus()):?>
            <div class="g-plusone" data-size="medium" <?php echo ($google_count >0 ? '' : 'data-annotation="none"'); ?> ></div>
        <?php endif ?>
    </div>    
</div>

